services:
  - type: web
    name: bodega
    env: python
    buildCommand: ./build.sh
    startCommand: gunicorn run:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.12
      - key: FLASK_APP
        value: run.py
      - key: FLASK_ENV
        value: production
      - key: PYTHONPATH
        value: . 